# Generated by Django 4.1 on 2022-08-26 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_rename_choices_choice_choice_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='status',
            field=models.CharField(choices=[('A', 'active'), ('E', 'ended'), ('F', 'future')], default='active', max_length=20),
        ),
    ]
