# Generated by Django 4.1 on 2022-08-31 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_question_voters'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='voters',
        ),
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voter', models.CharField(default='', max_length=50)),
                ('voted_question', models.ManyToManyField(to='polls.question')),
            ],
        ),
    ]
