# Generated by Django 4.1 on 2022-08-31 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_remove_question_voters_voter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voter',
            name='voter',
        ),
        migrations.AddField(
            model_name='voter',
            name='name',
            field=models.CharField(default=True, max_length=200),
            preserve_default=False,
        ),
    ]
