# Generated by Django 4.1 on 2022-08-31 09:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0006_remove_voter_voter_voter_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='voters',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='sender',
            field=models.CharField(default=True, max_length=200),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Voter',
        ),
    ]
