# Generated by Django 4.1 on 2022-08-31 10:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0007_choice_voters_question_sender_delete_voter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='voters',
        ),
        migrations.CreateModel(
            name='Voterinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=200)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('p_choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.choice')),
            ],
        ),
        migrations.AddField(
            model_name='choice',
            name='voters',
            field=models.CharField(default=False, max_length=200),
            preserve_default=False,
        ),
    ]
