# Generated by Django 4.1 on 2022-08-31 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_remove_choice_voters_voterinfo_choice_voters'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voterinfo',
            name='p_choice',
        ),
        migrations.AddField(
            model_name='voterinfo',
            name='poll_text',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='polls.question'),
            preserve_default=False,
        ),
    ]
