# Generated by Django 4.1 on 2022-08-31 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_remove_voterinfo_p_choice_voterinfo_poll_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voterinfo',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
