# Generated by Django 4.1 on 2022-08-31 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_rename_voterinfo_voteinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='voters',
        ),
    ]
