# Generated by Django 4.1 on 2022-09-01 07:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0016_alter_voteinfo_answer_alter_voteinfo_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='sender',
        ),
        migrations.AddField(
            model_name='question',
            name='author',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
